version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
    overwrite: true

permissions:
  - object: /var/www/myapp
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: ec2-user
