version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_install:
    commands:
      - echo "Running test..."
      - npm test

  build:
    commands:
      - echo "Build started..."

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - 'node_modules/**/*'
